# Generated by Django 2.1.1 on 2020-03-28 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_auto_20200328_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
